name: Build Tweak

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: theos/theos:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Tweak
        run: |
          # تثبيت الأدوات اللازمة إذا لزم الأمر
          make clean
          make package
          
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: MoustacheMod-Package
          path: packages/*.deb
