name: Build Moustache Mod Menu

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Environment
      run: |
        brew install ldid xz
        git clone --recursive https://github.com ~/theos
        git clone https://github.com ~/theos/sdks

    - name: Compile Package
      run: |
        export THEOS=~/theos
        export PATH=~/theos/bin:$PATH
        make package FINALPACKAGE=1

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MoustacheMenu-DEB
        path: packages/*.deb
