TWEAK_NAME = MoustacheMenu

MoustacheMenu_FILES = main.mm
MoustacheMenu_FRAMEWORKS = UIKit CoreGraphics QuartzCore
MoustacheMenu_CFLAGS = -fobjc-arc -Wno-deprecated-declarations -Wno-unused-variable -Wno-unused-function

include $(THEOS_MAKE_PATH)/tweak.mk

